"""empty message

Revision ID: 75512c09f02d
Revises: d1364d39bd70
Create Date: 2025-03-06 18:08:49.581745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75512c09f02d'
down_revision = 'd1364d39bd70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_usuario', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images_groups', schema=None) as batch_op:
        batch_op.drop_column('group_usuario')

    # ### end Alembic commands ###
